name: nova-food

services:
  postgres:
    image: postgres:13
    container_name: nova-food-postgres
    environment:
      POSTGRES_USER: nova_food
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: nova_food
    ports:
      - "15432:5432"
    volumes:
      - nova_food_postgres_data:/var/lib/postgresql/data

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: nova-food-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - nova_food_zookeeper_data:/data
      - nova_food_zookeeper_log:/datalog

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: nova-food-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - nova_food_kafka_data:/var/lib/kafka/data

volumes:
  nova_food_postgres_data:
  nova_food_zookeeper_data:
  nova_food_zookeeper_log:
  nova_food_kafka_data:
